server:
  port: 8081
spring:
  application:
    name: app-ribbon
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/