server:
  port: 8082
spring:
  application:
    name: app-zuul
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
zuul:
  routes:
    test-service:
      path: /api/**
      serviceId: service-provider
ribbon:
  ReadTimeout: 6000
  ConnectionTimeout: 6000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
      fallback:
        # 是否开启回退方法
        enabled: true