server:
  port: 8082
spring:
  application:
    name: app-zuul
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
zuul:
  routes:
    test-service:
      path: /api/**
      serviceId: service-provider