server:
  port: 8083
spring:
  application:
    name: app-fegign
  security:
    user:
      name: admin
      password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka/
feign:
  hystrix:
    enabled: true